// regionCodes.ts
export interface RegionCode {
  code: string;
  name: string;
  svgId: string;
}

export const regionCodes: RegionCode[] = [
  // 서울특별시
  { code: "11110", name: "서울특별시 종로구", svgId: "종로구" },
  { code: "11140", name: "서울특별시 중구", svgId: "중구" },
  { code: "11170", name: "서울특별시 용산구", svgId: "용산구" },
  { code: "11200", name: "서울특별시 성동구", svgId: "성동구" },
  { code: "11215", name: "서울특별시 광진구", svgId: "광진구" },
  { code: "11230", name: "서울특별시 동대문구", svgId: "동대문구" },
  { code: "11260", name: "서울특별시 중랑구", svgId: "중랑구" },
  { code: "11290", name: "서울특별시 성북구", svgId: "성북구" },
  { code: "11305", name: "서울특별시 강북구", svgId: "강북구" },
  { code: "11320", name: "서울특별시 도봉구", svgId: "도봉구" },
  { code: "11350", name: "서울특별시 노원구", svgId: "노원구" },
  { code: "11380", name: "서울특별시 은평구", svgId: "은평구" },
  { code: "11410", name: "서울특별시 서대문구", svgId: "서대문구" },
  { code: "11440", name: "서울특별시 마포구", svgId: "마포구" },
  { code: "11470", name: "서울특별시 양천구", svgId: "양천구" },
  { code: "11500", name: "서울특별시 강서구", svgId: "강서구" },
  { code: "11530", name: "서울특별시 구로구", svgId: "구로구" },
  { code: "11545", name: "서울특별시 금천구", svgId: "금천구" },
  { code: "11560", name: "서울특별시 영등포구", svgId: "영등포구" },
  { code: "11590", name: "서울특별시 동작구", svgId: "동작구" },
  { code: "11620", name: "서울특별시 관악구", svgId: "관악구" },
  { code: "11650", name: "서울특별시 서초구", svgId: "서초구" },
  { code: "11680", name: "서울특별시 강남구", svgId: "강남구" },
  { code: "11710", name: "서울특별시 송파구", svgId: "송파구" },
  { code: "11740", name: "서울특별시 강동구", svgId: "강동구" },

  // 부산광역시
  {
    code: "26110",
    name: "부산광역시 중구",
    svgId: "중구",
  },
  {
    code: "26140",
    name: "부산광역시 서구",
    svgId: "서구",
  },
  {
    code: "26170",
    name: "부산광역시 동구",
    svgId: "동구",
  },
  { code: "26200", name: "부산광역시 영도구", svgId: "영도구" },
  { code: "26230", name: "부산광역시 부산진구", svgId: "부산진구" },
  { code: "26260", name: "부산광역시 동래구", svgId: "동래구" },
  {
    code: "26290",
    name: "부산광역시 남구",
    svgId: "남구",
  },
  {
    code: "26320",
    name: "부산광역시 북구",
    svgId: "북구",
  },
  { code: "26350", name: "부산광역시 해운대구", svgId: "해운대구" },
  { code: "26380", name: "부산광역시 사하구", svgId: "사하구" },
  { code: "26410", name: "부산광역시 금정구", svgId: "금정구" },
  {
    code: "26440",
    name: "부산광역시 강서구",
    svgId: "강서구",
  },
  { code: "26470", name: "부산광역시 연제구", svgId: "연제구" },
  { code: "26500", name: "부산광역시 수영구", svgId: "수영구" },
  { code: "26530", name: "부산광역시 사상구", svgId: "사상구" },
  { code: "26710", name: "부산광역시 기장군", svgId: "기장군" },

  // 대구광역시
  {
    code: "27110",
    name: "대구광역시 중구",
    svgId: "중구",
  },
  {
    code: "27140",
    name: "대구광역시 동구",
    svgId: "동구",
  },
  {
    code: "27170",
    name: "대구광역시 서구",
    svgId: "서구",
  },
  { code: "27200", name: "대구광역시 남구", svgId: "남구" },
  { code: "27230", name: "대구광역시 북구", svgId: "북구" },
  { code: "27260", name: "대구광역시 수성구", svgId: "수성구" },
  { code: "27290", name: "대구광역시 달서구", svgId: "달서구" },
  { code: "27710", name: "대구광역시 달성군", svgId: "달성군" },
  { code: "27720", name: "대구광역시 군위군", svgId: "군위군" },

  // 인천광역시
  {
    code: "28110",
    name: "인천광역시 중구",
    svgId: "중구",
  },
  { code: "28140", name: "인천광역시 동구", svgId: "동구" },
  { code: "28177", name: "인천광역시 미추홀구", svgId: "미추홀구" },
  { code: "28185", name: "인천광역시 연수구", svgId: "연수구" },
  { code: "28200", name: "인천광역시 남동구", svgId: "남동구" },
  { code: "28237", name: "인천광역시 부평구", svgId: "부평구" },
  { code: "28245", name: "인천광역시 계양구", svgId: "계양구" },
  { code: "28260", name: "인천광역시 서구", svgId: "서구" },
  { code: "28710", name: "인천광역시 강화군", svgId: "강화군" },
  { code: "28720", name: "인천광역시 옹진군", svgId: "옹진군" },

  // 광주광역시
  {
    code: "29110",
    name: "광주광역시 동구",
    svgId: "동구",
  },
  {
    code: "29140",
    name: "광주광역시 서구",
    svgId: "서구",
  },
  {
    code: "29155",
    name: "광주광역시 남구",
    svgId: "남구",
  },
  {
    code: "29170",
    name: "광주광역시 북구",
    svgId: "북구",
  },
  { code: "29200", name: "광주광역시 광산구", svgId: "광산구" },

  // 대전광역시
  {
    code: "30110",
    name: "대전광역시 동구",
    svgId: "동구",
  },
  {
    code: "30140",
    name: "대전광역시 중구",
    svgId: "중구",
  },
  {
    code: "30170",
    name: "대전광역시 서구",
    svgId: "서구",
  },
  { code: "30200", name: "대전광역시 유성구", svgId: "유성구" },
  { code: "30230", name: "대전광역시 대덕구", svgId: "대덕구" },

  // 울산광역시
  {
    code: "31110",
    name: "울산광역시 중구",
    svgId: "중구",
  },
  {
    code: "31140",
    name: "울산광역시 남구",
    svgId: "남구_00000116235787361681521350000007395983019771300517_",
  },
  {
    code: "31170",
    name: "울산광역시 동구",
    svgId: "동구",
  },
  {
    code: "31200",
    name: "울산광역시 북구",
    svgId: "북구",
  },
  { code: "31710", name: "울산광역시 울주군", svgId: "울주군" },

  // 세종특별자치시
  {
    code: "36110",
    name: "세종특별자치시",
    svgId: "세종특별자치시",
  },

  // 경기도
  { code: "41111", name: "경기도 수원시 장안구", svgId: "수원시_장안구" },
  { code: "41113", name: "경기도 수원시 권선구", svgId: "수원시_권선구" },
  { code: "41115", name: "경기도 수원시 팔달구", svgId: "수원시_팔달구" },
  { code: "41117", name: "경기도 수원시 영통구", svgId: "수원시_영통구" },
  { code: "41131", name: "경기도 성남시 수정구", svgId: "성남시_수정구" },
  { code: "41133", name: "경기도 성남시 중원구", svgId: "성남시_중원구" },
  { code: "41135", name: "경기도 성남시 분당구", svgId: "성남시_분당구" },
  { code: "41150", name: "경기도 의정부시", svgId: "의정부시" },
  { code: "41171", name: "경기도 안양시 만안구", svgId: "안양시_만안구" },
  { code: "41173", name: "경기도 안양시 동안구", svgId: "안양시_동안구" },
  { code: "41190", name: "경기도 부천시", svgId: "부천시" },
  { code: "41210", name: "경기도 광명시", svgId: "광명시" },
  { code: "41220", name: "경기도 평택시", svgId: "평택시" },
  { code: "41250", name: "경기도 동두천시", svgId: "동두천시" },
  { code: "41271", name: "경기도 안산시 상록구", svgId: "안산시_상록구" },
  {
    code: "41273",
    name: "경기도 안산시 단원구",
    svgId: "안산시_단원구",
  },
  { code: "41281", name: "경기도 고양시 덕양구", svgId: "고양시_덕양구" },
  { code: "41285", name: "경기도 고양시 일산동구", svgId: "고양시_일산동구" },
  { code: "41287", name: "경기도 고양시 일산서구", svgId: "고양시_일산서구" },
  { code: "41290", name: "경기도 과천시", svgId: "과천시" },
  { code: "41310", name: "경기도 구리시", svgId: "구리시" },
  { code: "41360", name: "경기도 남양주시", svgId: "남양주시" },
  { code: "41370", name: "경기도 오산시", svgId: "오산시" },
  { code: "41390", name: "경기도 시흥시", svgId: "시흥시" },
  { code: "41410", name: "경기도 군포시", svgId: "군포시" },
  { code: "41430", name: "경기도 의왕시", svgId: "의왕시" },
  { code: "41450", name: "경기도 하남시", svgId: "하남시" },
  { code: "41461", name: "경기도 용인시 처인구", svgId: "용인시_처인구" },
  { code: "41463", name: "경기도 용인시 기흥구", svgId: "용인시_기흥구" },
  { code: "41465", name: "경기도 용인시 수지구", svgId: "용인시_수지구" },
  { code: "41480", name: "경기도 파주시", svgId: "파주시" },
  { code: "41500", name: "경기도 이천시", svgId: "이천시" },
  { code: "41550", name: "경기도 안성시", svgId: "안성시" },
  { code: "41570", name: "경기도 김포시", svgId: "김포시" },
  { code: "41590", name: "경기도 화성시", svgId: "화성시" },
  { code: "41610", name: "경기도 광주시", svgId: "광주시" },
  { code: "41630", name: "경기도 양주시", svgId: "양주시" },
  { code: "41650", name: "경기도 포천시", svgId: "포천시" },
  { code: "41670", name: "경기도 여주시", svgId: "여주시" },
  { code: "41800", name: "경기도 연천군", svgId: "연천군" },
  { code: "41820", name: "경기도 가평군", svgId: "가평군" },
  { code: "41830", name: "경기도 양평군", svgId: "양평군" },

  // 충청북도
  { code: "43111", name: "충청북도 청주시 상당구", svgId: "청주시_상당구" },
  { code: "43112", name: "충청북도 청주시 서원구", svgId: "청주시_서원구" },
  { code: "43113", name: "충청북도 청주시 흥덕구", svgId: "청주시_흥덕구" },
  { code: "43114", name: "충청북도 청주시 청원구", svgId: "청주시_청원구" },
  { code: "43130", name: "충청북도 충주시", svgId: "충주시" },
  { code: "43150", name: "충청북도 제천시", svgId: "제천시" },
  { code: "43720", name: "충청북도 보은군", svgId: "보은군" },
  { code: "43730", name: "충청북도 옥천군", svgId: "옥천군" },
  { code: "43740", name: "충청북도 영동군", svgId: "영동군" },
  { code: "43745", name: "충청북도 증평군", svgId: "증평군" },
  { code: "43750", name: "충청북도 진천군", svgId: "진천군" },
  { code: "43760", name: "충청북도 괴산군", svgId: "괴산군" },
  { code: "43770", name: "충청북도 음성군", svgId: "음성군" },
  { code: "43800", name: "충청북도 단양군", svgId: "단양군" },

  // 충청남도
  { code: "44131", name: "충청남도 천안시 동남구", svgId: "천안시_동남구" },
  { code: "44133", name: "충청남도 천안시 서북구", svgId: "천안시_서북구" },
  { code: "44150", name: "충청남도 공주시", svgId: "공주시" },
  { code: "44180", name: "충청남도 보령시", svgId: "보령시" },
  { code: "44200", name: "충청남도 아산시", svgId: "아산시" },
  { code: "44210", name: "충청남도 서산시", svgId: "서산시" },
  { code: "44230", name: "충청남도 논산시", svgId: "논산시" },
  { code: "44250", name: "충청남도 계룡시", svgId: "계룡시" },
  { code: "44270", name: "충청남도 당진시", svgId: "당진시" },
  { code: "44710", name: "충청남도 금산군", svgId: "금산군" },
  { code: "44760", name: "충청남도 부여군", svgId: "부여군" },
  { code: "44770", name: "충청남도 서천군", svgId: "서천군" },
  { code: "44790", name: "충청남도 청양군", svgId: "청양군" },
  { code: "44800", name: "충청남도 홍성군", svgId: "홍성군" },
  { code: "44810", name: "충청남도 예산군", svgId: "예산군" },
  { code: "44825", name: "충청남도 태안군", svgId: "태안군" },

  // 전라북도
  { code: "45111", name: "전라북도 전주시 완산구", svgId: "전주시_완산구" },
  { code: "45113", name: "전라북도 전주시 덕진구", svgId: "전주시_덕진구" },
  { code: "45130", name: "전라북도 군산시", svgId: "군산시" },
  { code: "45140", name: "전라북도 익산시", svgId: "익산시" },
  { code: "45180", name: "전라북도 정읍시", svgId: "정읍시" },
  { code: "45190", name: "전라북도 남원시", svgId: "남원시" },
  { code: "45210", name: "전라북도 김제시", svgId: "김제시" },
  { code: "45710", name: "전라북도 완주군", svgId: "완주군" },
  { code: "45720", name: "전라북도 진안군", svgId: "진안군" },
  { code: "45730", name: "전라북도 무주군", svgId: "무주군" },
  { code: "45740", name: "전라북도 장수군", svgId: "장수군" },
  { code: "45750", name: "전라북도 임실군", svgId: "임실군" },
  { code: "45770", name: "전라북도 순창군", svgId: "순창군" },
  { code: "45790", name: "전라북도 고창군", svgId: "고창군" },
  { code: "45800", name: "전라북도 부안군", svgId: "부안군" },

  // 전라남도
  { code: "46110", name: "전라남도 목포시", svgId: "목포시" },
  { code: "46130", name: "전라남도 여수시", svgId: "여수시" },
  { code: "46150", name: "전라남도 순천시", svgId: "순천시" },
  { code: "46170", name: "전라남도 나주시", svgId: "나주시" },
  { code: "46230", name: "전라남도 광양시", svgId: "광양시" },
  { code: "46710", name: "전라남도 담양군", svgId: "담양군" },
  { code: "46720", name: "전라남도 곡성군", svgId: "곡성군" },
  { code: "46730", name: "전라남도 구례군", svgId: "구례군" },
  { code: "46770", name: "전라남도 고흥군", svgId: "고흥군" },
  { code: "46780", name: "전라남도 보성군", svgId: "보성군" },
  { code: "46790", name: "전라남도 화순군", svgId: "화순군" },
  { code: "46800", name: "전라남도 장흥군", svgId: "장흥군" },
  { code: "46810", name: "전라남도 강진군", svgId: "강진군" },
  { code: "46820", name: "전라남도 해남군", svgId: "해남군" },
  { code: "46830", name: "전라남도 영암군", svgId: "영암군" },
  { code: "46840", name: "전라남도 무안군", svgId: "무안군" },
  { code: "46860", name: "전라남도 함평군", svgId: "함평군" },
  { code: "46870", name: "전라남도 영광군", svgId: "영광군" },
  { code: "46880", name: "전라남도 장성군", svgId: "장성군" },
  { code: "46890", name: "전라남도 완도군", svgId: "완도군" },
  { code: "46900", name: "전라남도 진도군", svgId: "진도군" },
  { code: "46910", name: "전라남도 신안군", svgId: "신안군" },

  // 경상북도
  { code: "47111", name: "경상북도 포항시 남구", svgId: "포항시_남구" },
  { code: "47113", name: "경상북도 포항시 북구", svgId: "포항시_북구" },
  { code: "47130", name: "경상북도 경주시", svgId: "경주시" },
  { code: "47150", name: "경상북도 김천시", svgId: "김천시" },
  { code: "47170", name: "경상북도 안동시", svgId: "안동시" },
  { code: "47190", name: "경상북도 구미시", svgId: "구미시" },
  { code: "47210", name: "경상북도 영주시", svgId: "영주시" },
  { code: "47230", name: "경상북도 영천시", svgId: "영천시" },
  { code: "47250", name: "경상북도 상주시", svgId: "상주시" },
  { code: "47280", name: "경상북도 문경시", svgId: "문경시" },
  { code: "47290", name: "경상북도 경산시", svgId: "경산시" },
  { code: "47730", name: "경상북도 의성군", svgId: "의성군" },
  { code: "47750", name: "경상북도 청송군", svgId: "청송군" },
  { code: "47760", name: "경상북도 영양군", svgId: "영양군" },
  { code: "47770", name: "경상북도 영덕군", svgId: "영덕군" },
  { code: "47820", name: "경상북도 청도군", svgId: "청도군" },
  { code: "47830", name: "경상북도 고령군", svgId: "고령군" },
  { code: "47840", name: "경상북도 성주군", svgId: "성주군" },
  { code: "47850", name: "경상북도 칠곡군", svgId: "칠곡군" },
  { code: "47900", name: "경상북도 예천군", svgId: "예천군" },
  { code: "47920", name: "경상북도 봉화군", svgId: "봉화군" },
  { code: "47930", name: "경상북도 울진군", svgId: "울진군" },
  { code: "47940", name: "경상북도 울릉군", svgId: "울릉군" },

  // 경상남도
  { code: "48121", name: "경상남도 창원시 의창구", svgId: "창원시_의창구" },
  { code: "48123", name: "경상남도 창원시 성산구", svgId: "창원시_성산구" },
  {
    code: "48125",
    name: "경상남도 창원시 마산합포구",
    svgId: "창원시_마산합포구",
  },
  {
    code: "48127",
    name: "경상남도 창원시 마산회원구",
    svgId: "창원시_마산회원구",
  },
  { code: "48129", name: "경상남도 창원시 진해구", svgId: "창원시_진해구" },
  { code: "48170", name: "경상남도 진주시", svgId: "진주시" },
  { code: "48220", name: "경상남도 통영시", svgId: "통영시" },
  { code: "48240", name: "경상남도 사천시", svgId: "사천시" },
  { code: "48250", name: "경상남도 김해시", svgId: "김해시" },
  { code: "48270", name: "경상남도 밀양시", svgId: "밀양시" },
  { code: "48310", name: "경상남도 거제시", svgId: "거제시" },
  { code: "48330", name: "경상남도 양산시", svgId: "양산시" },
  { code: "48720", name: "경상남도 의령군", svgId: "의령군" },
  { code: "48730", name: "경상남도 함안군", svgId: "함안군" },
  { code: "48740", name: "경상남도 창녕군", svgId: "창녕군" },
  {
    code: "48820",
    name: "경상남도 고성군",
    svgId: "고성군",
  },
  { code: "48840", name: "경상남도 남해군", svgId: "남해군" },
  { code: "48850", name: "경상남도 하동군", svgId: "하동군" },
  { code: "48860", name: "경상남도 산청군", svgId: "산청군" },
  { code: "48870", name: "경상남도 함양군", svgId: "함양군" },
  { code: "48880", name: "경상남도 거창군", svgId: "거창군" },
  { code: "48890", name: "경상남도 합천군", svgId: "합천군" },

  // 제주특별자치도
  { code: "50110", name: "제주특별자치도 제주시", svgId: "제주시" },
  { code: "50130", name: "제주특별자치도 서귀포시", svgId: "서귀포시" },

  // 강원특별자치도
  { code: "51110", name: "강원특별자치도 춘천시", svgId: "춘천시" },
  { code: "51130", name: "강원특별자치도 원주시", svgId: "원주시" },
  { code: "51150", name: "강원특별자치도 강릉시", svgId: "강릉시" },
  { code: "51170", name: "강원특별자치도 동해시", svgId: "동해시" },
  { code: "51190", name: "강원특별자치도 태백시", svgId: "태백시" },
  { code: "51210", name: "강원특별자치도 속초시", svgId: "속초시" },
  { code: "51230", name: "강원특별자치도 삼척시", svgId: "삼척시" },
  { code: "51720", name: "강원특별자치도 홍천군", svgId: "홍천군" },
  { code: "51730", name: "강원특별자치도 횡성군", svgId: "횡성군" },
  { code: "51750", name: "강원특별자치도 영월군", svgId: "영월군" },
  { code: "51760", name: "강원특별자치도 평창군", svgId: "평창군" },
  { code: "51770", name: "강원특별자치도 정선군", svgId: "정선군" },
  { code: "51780", name: "강원특별자치도 철원군", svgId: "철원군" },
  { code: "51790", name: "강원특별자치도 화천군", svgId: "화천군" },
  { code: "51800", name: "강원특별자치도 양구군", svgId: "양구군" },
  { code: "51810", name: "강원특별자치도 인제군", svgId: "인제군" },
  { code: "51820", name: "강원특별자치도 고성군", svgId: "고성군" },
  { code: "51830", name: "강원특별자치도 양양군", svgId: "양양군" },
];

// SVG ID로 지역 코드 찾기
export const getRegionBysvgId = (svgId: string): RegionCode | undefined => {
  return regionCodes.find((region) => region.svgId === svgId);
};

// 지역 코드로 SVG ID 찾기
export const getSvgIdByCode = (code: string): string | undefined => {
  return regionCodes.find((region) => region.code === code)?.svgId;
};
